name: CI
on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          cd /usr/local/www/ && git pull git@github.com:wishxam/wishxam.github.io.git master:master
